apiVersion: v1
kind: Secret
metadata:
  name: geomarker-auth-secrets
  namespace: geomarker
type: Opaque
stringData:
  SYMMETRIC_SECURITY_KEY:
  SigningCertificatePassword:
---
apiVersion: v1
kind: Secret
metadata:
  name: geomarker-azuread-secrets
  namespace: geomarker
type: Opaque
stringData:
  EXTERNAL_LOGIN_ID:
  EXTERNAL_LOGIN_SECRET:
---
apiVersion: v1
kind: Secret
metadata:
  name: geomarker-mysql-secrets
  namespace: geomarker
type: Opaque
stringData:
  MYSQL_HOST:
  MYSQL_USER:
  MYSQL_PASSWORD:
---
apiVersion: v1
kind: Secret
metadata:
  name: geomarker-logging-secrets
  namespace: geomarker
type: Opaque
stringData:
  APPLICATIONINSIGHTS_CONNECTION_STRING:
---
apiVersion: v1
kind: Secret
metadata:
  name: geomarker-nfsstorage-secrets
  namespace: geomarker
stringData:
  azurestorageaccountname: geomarkerpnfs01
  azurestorageaccountkey:
