parameters:
  - name: override
    displayName: Override Branch Deployment
    type: boolean
    default: false

variables:
  driveTimeVersionNumber: 0.0.0
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  isPullRequest: $[eq(variables['Build.Reason'], 'PullRequest')]

stages:
- stage: DeployProductionDriveTime
  condition: or(and(eq(variables.isMain, true), eq(variables.isPullRequest, false)), eq(${{ parameters.override }}, true))
  jobs:
  - deployment: ProductionDeploymentDriveTime
    displayName: Production Deployment of DriveTime Service
    pool:
      name: Local Build Agent
    environment: 'GeoMarker Frontiers Production - ACR'
    workspace:
      clean: all
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - powershell: |
                $DRIVETIMEVERSION = Get-Content "$Env:BUILD_SOURCESDIRECTORY/GeoMarker.Frontiers/GeoMarker.Frontiers.DriveTime/VERSION"
                Write-Host "##vso[task.setvariable variable=driveTimeVersionNumber;]$DRIVETIMEVERSION"
          - task: Docker@2
            displayName: 'Login to ACR'
            inputs:
              containerRegistry: $(AZ_ACR)
              command: 'login'
          - task: Docker@2
            displayName: 'Build and Push DriveTime'
            inputs:
              command: 'buildAndPush'
              containerRegistry: $(AZ_ACR)
              repository: 'geomarker.frontiers.drivetime'
              Dockerfile: '$(Build.SourcesDirectory)/GeoMarker.Frontiers/GeoMarker.Frontiers.DriveTime/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)/GeoMarker.Frontiers'
              tags: |
                latest
                $(driveTimeVersionNumber)
