parameters:
  - name: override
    displayName: Override Branch Deployment
    type: boolean
    default: false

variables:
  geoCodeVersionNumber: 0.0.0
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  isPullRequest: $[eq(variables['Build.Reason'], 'PullRequest')]

stages:
- stage: DeployProductionGeoCode
  condition: or(and(eq(variables.isMain, true), eq(variables.isPullRequest, false)), eq(${{ parameters.override }}, true))
  jobs:
  - deployment: ProductionDeploymentGeoCode
    displayName: Production Deployment of GeoCode Service
    pool:
      name: Local Build Agent
    environment: 'GeoMarker Frontiers Production - ACR'
    workspace:
      clean: all
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - powershell: |
                $GEOCODEVERSION = Get-Content "$Env:BUILD_SOURCESDIRECTORY/GeoMarker.Frontiers/GeoMarker.Frontiers.GeoCode/VERSION"
                Write-Host "##vso[task.setvariable variable=geoCodeVersionNumber;]$GEOCODEVERSION"
          - task: Docker@2
            displayName: 'Login to ACR'
            inputs:
              containerRegistry: $(AZ_ACR)
              command: 'login'
          - task: Docker@2
            displayName: 'Build and Push GeoCode'
            inputs:
              command: 'buildAndPush'
              containerRegistry: $(AZ_ACR)
              repository: 'geomarker.frontiers.geocode'
              Dockerfile: '$(Build.SourcesDirectory)/GeoMarker.Frontiers/GeoMarker.Frontiers.GeoCode/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)/GeoMarker.Frontiers'
              tags: |
                latest
                $(geoCodeVersionNumber)
